# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master  # This triggers the pipeline on changes to the main branch


jobs:
- job: ImportToGitHub
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      git clone --mirror https://DaisyOrg@dev.azure.com/DaisyOrg/Test%20Projects/_git/Test_Shipping_to_Github
      cd Test_Shipping_to_Github.git
      git remote add github https://github.com/AruseyDaisy/Test_Shipping_From_AzureADO_to_GitHub.git
      git push --mirror github
    displayName: 'Import ADO Repo to GitHub'