# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master  # This triggers the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:

# Checkout the ADO repo
- checkout: self

# Set up GitHub remote
- script: |
    git remote add github https://AruseyDaisy:$(GITHUBTOKEN)@github.com/AruseyDaisy/Test_Shipping_From_AzureADO_to_GitHub.git
    git push github --mirror
  displayName: 'Push to GitHub' 

