# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
    - master
pool:
      vmImage: 'ubuntu-latest'
  
steps:
    - checkout: self
    - script: |
        git config --global user.email "daisyarusey.dc@gmail.com"
        git config --global user.name "Daisy Arusey"
        git remote add origin https://github.com/AruseyDaisy/Test_Shipping_From_AzureADO_to_GitHub.git
        git branch -M main
        git push -u origin main
      env:
        GITHUB_TOKEN: $(GitHubToken)