# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master  # This triggers the pipeline on changes to the main branch


jobs:
- job: ExportToGitHub
  displayName: Export to GitHub
  steps:
    - checkout: self  # Check out the Azure DevOps repository
      persistCredentials: true

    - script: |
        git fetch --all
        git checkout master
      displayName: "Fetch all branches and checkout master"

    # Set up Git to authenticate with GitHub
    - script: |
        git config --global user.email "daisyarusey.dc@gmail.com"
        git config --global user.name "AruseyDaisy"
      displayName: "Configure Git"

    - script: |
        git remote add github https://$(GITHUB_TOKEN)@github.com/AruseyDaisy/Test_Shipping_From_AzureADO_to_GitHub.git
        git push -u github master:main --force
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)
      displayName: "Push to GitHub"